name: Actions 😎

on:
  pull_request: {}
  push: { branches: [main] }

uses: webbertakken/unity-test-runner@v1.4
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
with:
  projectPath: path/to/your/project
  unityVersion: 2020.1.13f1

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2020.1.13f1
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build

      - name: Debug
        run: |
          echo ${PWD}
          ls -alh
